# Generated by Django 5.2.6 on 2025-09-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subtotal', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending')),
                ('payment_method', models.CharField(choices=[('paystack', 'paystack'), ('paypal', 'paypal'), ('fluter', 'fluter')], default='paystack')),
                ('payment_completed', models.BooleanField(default=False)),
                ('ref', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
            ],
        ),
    ]
